# Generated by Django 4.0.6 on 2024-09-29 08:03

from django.db import migrations, models
import user_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_alter_profile_agree_save_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='agree_save_data',
            field=models.BooleanField(default=True, verbose_name='Save persona data'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=user_auth.models.generate_profile_images_path, verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=15, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=15, verbose_name='Middle name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Phone number'),
        ),
    ]
