# Generated by Django 4.0.6 on 2024-09-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_alter_profile_agree_save_data_alter_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='agree_save_data',
            field=models.BooleanField(default=True, verbose_name='Save personal data'),
        ),
    ]
