# Generated by Django 4.0.6 on 2024-09-29 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_alter_order_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'price'], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
